<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="18" total="19" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="s1" duration-ms="41002" started-at="2017-12-10T09:31:12Z" finished-at="2017-12-10T09:31:53Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="41002" started-at="2017-12-10T09:31:12Z" finished-at="2017-12-10T09:31:53Z">
      <class name="test.Massage">
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3020" started-at="2017-12-10T17:31:21Z" data-provider="s1" finished-at="2017-12-10T17:31:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[马佳烁1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3016" started-at="2017-12-10T17:31:24Z" data-provider="s1" finished-at="2017-12-10T17:31:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[马佳烁，]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3071" started-at="2017-12-10T17:31:27Z" data-provider="s1" finished-at="2017-12-10T17:31:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[马佳烁123.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3002" started-at="2017-12-10T17:31:30Z" data-provider="s1" finished-at="2017-12-10T17:31:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3013" started-at="2017-12-10T17:31:33Z" data-provider="s1" finished-at="2017-12-10T17:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3013" started-at="2017-12-10T17:31:36Z" data-provider="s1" finished-at="2017-12-10T17:31:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3013" started-at="2017-12-10T17:31:39Z" data-provider="s1" finished-at="2017-12-10T17:31:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[m]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3013" started-at="2017-12-10T17:31:42Z" data-provider="s1" finished-at="2017-12-10T17:31:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[mxjmjs..]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[mxjmjs..]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
        <test-method status="FAIL" signature="testAddMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Massage@7f9a81e8]" name="testAddMessage" duration-ms="3014" started-at="2017-12-10T17:31:45Z" data-provider="s1" finished-at="2017-12-10T17:31:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[马佳烁]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234678@qq.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[majiashuo]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddMassage.input(AddMassage.java:13)
	at test.Massage.testAddMessage(Massage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddMessage -->
      </class> <!-- test.Massage -->
      <class name="test.Shopping">
        <test-method status="FAIL" signature="testAddShopping()[pri:0, instance:test.Shopping@62ee68d8]" name="testAddShopping" duration-ms="21" started-at="2017-12-10T17:31:21Z" finished-at="2017-12-10T17:31:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddShopping.addgoods(AddShopping.java:12)
	at test.Shopping.testAddShopping(Shopping.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddShopping -->
        <test-method status="FAIL" signature="testDeleteShopping()[pri:0, instance:test.Shopping@62ee68d8]" name="testDeleteShopping" duration-ms="5" started-at="2017-12-10T17:31:21Z" finished-at="2017-12-10T17:31:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.DeleteShopping.delete(DeleteShopping.java:12)
	at test.Shopping.testDeleteShopping(Shopping.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteShopping -->
      </class> <!-- test.Shopping -->
      <class name="test.Address">
        <test-method status="FAIL" signature="testDeleteAddress()[pri:0, instance:test.Address@51081592]" name="testDeleteAddress" duration-ms="19" started-at="2017-12-10T17:31:21Z" finished-at="2017-12-10T17:31:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.DeleteAddress.delete(DeleteAddress.java:13)
	at test.Address.testDeleteAddress(Address.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteAddress -->
        <test-method status="FAIL" signature="testAddAddress(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Address@51081592]" name="testAddAddress" duration-ms="3020" started-at="2017-12-10T17:31:21Z" data-provider="s3" finished-at="2017-12-10T17:31:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[马佳烁]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[浙江省]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[杭州市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[临安市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[40号]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[18323145678]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddAddress.input(AddAddress.java:15)
	at test.Address.testAddAddress(Address.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAddress -->
        <test-method status="FAIL" signature="testAddAddress(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Address@51081592]" name="testAddAddress" duration-ms="3016" started-at="2017-12-10T17:31:24Z" data-provider="s3" finished-at="2017-12-10T17:31:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[张晓明]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[黑龙江省]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[哈尔滨市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[松北区]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[14栋3号]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[13323456789]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[234554]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddAddress.input(AddAddress.java:15)
	at test.Address.testAddAddress(Address.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAddress -->
        <test-method status="FAIL" signature="testAddAddress(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Address@51081592]" name="testAddAddress" duration-ms="3014" started-at="2017-12-10T17:31:27Z" data-provider="s3" finished-at="2017-12-10T17:31:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[李晓红]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[福建省]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[福州市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[鼓楼区]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[2栋工业]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[15532155678]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[890890]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddAddress.input(AddAddress.java:15)
	at test.Address.testAddAddress(Address.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAddress -->
        <test-method status="FAIL" signature="testAddAddress(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Address@51081592]" name="testAddAddress" duration-ms="3026" started-at="2017-12-10T17:31:30Z" data-provider="s3" finished-at="2017-12-10T17:31:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[张婷婷]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[山东省]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[济南市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[天桥区]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[3号写字楼]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[18032834432]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[234678]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddAddress.input(AddAddress.java:15)
	at test.Address.testAddAddress(Address.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAddress -->
        <test-method status="FAIL" signature="testAddAddress(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.Address@51081592]" name="testAddAddress" duration-ms="3005" started-at="2017-12-10T17:31:33Z" data-provider="s3" finished-at="2017-12-10T17:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[何建一]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[上海市]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[上海市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[黄浦区]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[邮局]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[15523456654]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[888999]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.AddAddress.input(AddAddress.java:15)
	at test.Address.testAddAddress(Address.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddAddress -->
      </class> <!-- test.Address -->
      <class name="test.PayShopping">
        <test-method status="FAIL" signature="testPay()[pri:0, instance:test.PayShopping@9629756]" name="testPay" duration-ms="32" started-at="2017-12-10T17:31:21Z" finished-at="2017-12-10T17:31:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at manage.Pay.pay(Pay.java:23)
	at test.PayShopping.testPay(PayShopping.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPay -->
      </class> <!-- test.PayShopping -->
      <class name="test.Login">
        <test-method status="PASS" signature="doBeforeMethod()[pri:0, instance:test.Login@396a51ab]" name="doBeforeMethod" is-config="true" duration-ms="8873" started-at="2017-12-10T17:31:12Z" finished-at="2017-12-10T17:31:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeMethod -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:test.Login@396a51ab]" name="testLogin" duration-ms="13566" started-at="2017-12-10T17:31:21Z" finished-at="2017-12-10T17:31:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:test.Login@396a51ab]" name="doAfterMethod" is-config="true" duration-ms="4879" started-at="2017-12-10T17:31:48Z" finished-at="2017-12-10T17:31:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- test.Login -->
    </test> <!-- Test -->
  </suite> <!-- s1 -->
</testng-results>
